image: Ubuntu  # образ для сборки

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - sudo curl -L https://github.com/docker/compose/releases/download/2.20.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker compose up -d
  - sleep 15
  - java -jar ./artifacts/aqa-shop.jar &
  - sleep 15

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info